### ISSUE TITLE
No tooltips in Rider 2023.3.2

### ISSUE THREAD

**Issue by nicholas-lmg** [RomanSoloweow/Rider-Visual-Studio-2019-Dark-Theme#11]
**Describe the bug**
Since the update to Rider 2023.3.2, this theme causes tooltips throughout the UI to no longer appear. Tooltips in the majority of the IDE interface are effected, with the notable exception that tooltips in the code editor itself are fine.

**To Reproduce**
1. Install Visual Studio 2019 Dark Theme 1.5.3
2. Install Rider 2023.3.2
3. Apply the theme
4. Hover the mouse cursor over a toolbar element such as 'Explorer'
5. Observe that no tooltip appears

**Expected behavior**
A tooltip should appear describing the element under the cursor.

**Screenshots**
![NoTooltips](https://github.com/RomanSoloweow/Rider-Visual-Studio-2019-Dark-Theme/assets/88295402/ef23c892-9d6b-453c-9fd5-59d92aceee8a)
Observe that tooltips work for the code, but not for the toolbar buttons or tab title.

**Desktop (please complete the following information):**
 - Version 1.5.3

**Additional context**
Began occurring in Rider 2023.2 or Rider 2023.3.2, uncertain which. Switching theme to _any_ other immediately resolves the issue.

**Comment by lofcz** [comment]
Thanks for fixing this! The thing was driving me crazy, I thought it was a bug in Rider.
