### ISSUE TITLE
Doesn't work with Rider 2021.1.3

### ISSUE THREAD

**Issue by netleader** [RomanSoloweow/Rider-Visual-Studio-2019-Dark-Theme#3]
I installed the plugin vie the JB website and it just themes the outer window but not the code area.

**Comment by RomanSoloweow** [comment]
Thank you for your interest
I use the plugin every day. The version of Rider I'm using is 2021.3.1, everything works.

Let's look for what the problem is, could you please send a screenshot

**Comment by netleader** [comment]
This is how it looks for me, I tried installing it via the plugins manager in Rider but it's the same result.
<img width="919" alt="Screenshot 2021-06-08 162559" src="https://user-images.githubusercontent.com/3867846/121203480-6ddf9f00-c876-11eb-8bb7-dda1010e02c5.png">

**Comment by netleader** [comment]
<img width="609" alt="Screenshot 2021-06-08 162915" src="https://user-images.githubusercontent.com/3867846/121203809-b1d2a400-c876-11eb-8552-fee574cce73b.png">

**Comment by RomanSoloweow** [comment]
You need to select a plugin in both sections
![image](https://user-images.githubusercontent.com/29205560/121212711-4395dd80-c886-11eb-9ec7-24c0d38bcdf5.png)

**Comment by netleader** [comment]
That was it 👯 nice thank you very much!!! Maybe worth an addition in the docs ;)

**Comment by RomanSoloweow** [comment]
Now I will definitely add, thank you very much! :)
