### ISSUE TITLE
Overwrite Editor Font

### ISSUE THREAD

**Issue by JacquesDoubell** [RomanSoloweow/Rider-Visual-Studio-2019-Dark-Theme#8]
**Describe the bug**
Changing the editor font doesn't work.

**To Reproduce**
1. Enable Rider's new ui (I haven't tried it with the current / 'old' ui)
2. Set the theme to VS 2019 Dark
3. Try to set the editor font to something else, e.g. JetBrains Mono
4. Editor font doesn't update to selected font

**Expected behavior**
The editor font should change.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Build #RD-223.8617.53, built on January 25, 2023

**Additional context**
I'm able to overwrite the font when using other themes.

**Comment by JacquesDoubell** [comment]
Nevermind, I found where to change it :)

It might be worth testing the theme with the new ui though.

**Comment by RomanSoloweow** [comment]
@JacquesDoubell 

Thanks for the question. Could you leave a little instruction for those who will face the same problem.
Thank you very much

**Comment by JacquesDoubell** [comment]
It's under Editor - Font:

![image](https://user-images.githubusercontent.com/113033749/217265246-986e03c8-859e-4b6c-91b3-d0e9acfca500.png)
